USE [CART2.0]
GO

/****** Object:  Table [dbo].[cart_cfpb_complaints_reg]    Script Date: 8/24/2024 6:52:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS [dbo].cart_cfpb_complaints_reg
go
CREATE TABLE [dbo].cart_cfpb_complaints_reg(
	[Complaint_ID]                  [int] NOT NULL,
	[Complaint_Text]                [varchar](max) NULL,
	[Company]                       [varchar](110) null,
	[State]                         [varchar](110) null,
	[Zip_Code]                      [varchar](10) null,
	[Product] [nvarchar](max) Null,
	[Sub_product] [nvarchar](max) Null,
	[Summarized_Complaint]          [varchar](max) null,
    [Reg_B_Classification]			[int]  NULL,
    [Reg_B_Explanation]             [varchar](max) NULL,
	[Reg_B_Solution]                [varchar](max) NULL,
	[Reg_B_Solution_Source]         [varchar](max) NULL,
    [Reg_C_Classification]			[int]  NULL,
    [Reg_C_Explanation]             [varchar](max) NULL,
	[Reg_C_Solution]                [varchar](max) NULL,
	[Reg_C_Solution_Source]         [varchar](max) NULL,
    [Reg_D_Classification]			[int]  NULL,
    [Reg_D_Explanation]             [varchar](max) NULL,
	[Reg_D_Solution]                [varchar](max) NULL,
	[Reg_D_Solution_Source]         [varchar](max) NULL,
    [Reg_E_Classification]			[int]  NULL,
    [Reg_E_Explanation]             [varchar](max) NULL,
	[Reg_E_Solution]                [varchar](max) NULL,
	[Reg_E_Solution_Source]         [varchar](max) NULL,
    [Reg_F_Classification]			[int]  NULL,
    [Reg_F_Explanation]             [varchar](max) NULL,
	[Reg_F_Solution]                [varchar](max) NULL,
	[Reg_F_Solution_Source]         [varchar](max) NULL,
    [Reg_G_Classification]			[int]  NULL,
    [Reg_G_Explanation]             [varchar](max) NULL,
	[Reg_G_Solution]                [varchar](max) NULL,
	[Reg_G_Solution_Source]         [varchar](max) NULL,
    [Reg_H_Classification]			[int]  NULL,
    [Reg_H_Explanation]				[varchar](max) NULL,
	[Reg_H_Solution]                [varchar](max) NULL,
	[Reg_H_Solution_Source]         [varchar](max) NULL,
    [Reg_I_Classification]			[int]  NULL,
    [Reg_I_Explanation]				[varchar](max) NULL,
	[Reg_I_Solution]                [varchar](max) NULL,
	[Reg_I_Solution_Source]         [varchar](max) NULL,
    [Reg_J_Classification]			[int]  NULL,
    [Reg_J_Explanation]				[varchar](max) NULL,
	[Reg_J_Solution]                [varchar](max) NULL,
	[Reg_J_Solution_Source]         [varchar](max) NULL,
    [Reg_K_Classification]			[int]  NULL,
    [Reg_K_Explanation]				[varchar](max) NULL,
	[Reg_K_Solution]                [varchar](max) NULL,
    [Reg_K_Solution_Source]         [varchar](max) NULL,
    [Reg_L_Classification]			[int]  NULL,
    [Reg_L_Explanation]				[varchar](max) NULL,
    [Reg_L_Solution]                [varchar](max) NULL,
    [Reg_L_Solution_Source]         [varchar](max) NULL,
    [Reg_M_Classification]			[int]  NULL,
    [Reg_M_Explanation]				[varchar](max) NULL,
    [Reg_M_Solution]                [varchar](max) NULL,
    [Reg_M_Solution_Source]         [varchar](max) NULL,
    [Reg_N_Classification]			[int]  NULL,
    [Reg_N_Explanation]				[varchar](max) NULL,
    [Reg_N_Solution]                [varchar](max) NULL,
    [Reg_N_Solution_Source]         [varchar](max) NULL,
    [Reg_O_Classification]			[int]  NULL,
    [Reg_O_Explanation]				[varchar](max) NULL,
    [Reg_O_Solution]                [varchar](max) NULL,
    [Reg_O_Solution_Source]         [varchar](max) NULL,
    [Reg_P_Classification]			[int]  NULL,
    [Reg_P_Explanation]				[varchar](max) NULL,
    [Reg_P_Solution]                [varchar](max) NULL,
    [Reg_P_Solution_Source]         [varchar](max) NULL,
    [Reg_V_Classification]			[int]  NULL,
    [Reg_V_Explanation] 			[varchar](max) NULL,
    [Reg_V_Solution]                [varchar](max) NULL,
    [Reg_V_Solution_Source]         [varchar](max) NULL,
    [Reg_X_Classification]			[int]  NULL,
    [Reg_X_Explanation]				[varchar](max) NULL,
    [Reg_X_Solution]                [varchar](max) NULL,
    [Reg_X_Solution_Source]         [varchar](max) NULL,
    [Reg_Z_Classification]			[int]  NULL,
    [Reg_Z_Explanation]				[varchar](max) NULL,
    [Reg_Z_Solution]                [varchar](max) NULL,
    [Reg_Z_Solution_Source]         [varchar](max) NULL,
    [Reg_CC_Classification]			[int]  NULL,
    [Reg_CC_Explanation]			[varchar](max) NULL,
    [Reg_CC_Solution]               [varchar](max) NULL,
    [Reg_CC_Solution_Source]        [varchar](max) NULL,
    [Reg_DD_Classification]			[int]  NULL,
    [Reg_DD_Explanation]			[varchar](max) NULL,
    [Reg_DD_Solution]               [varchar](max) NULL,
    [Reg_DD_Solution_Source]        [varchar](max) NULL,
    [Reg_AA_Classification]			[int]  NULL,
    [Reg_AA_Explanation]			[varchar](max) NULL,
    [Reg_AA_Solution]               [varchar](max) NULL,
    [Reg_AA_Solution_Source]        [varchar](max) NULL,
	[Loaded_By]                     [varchar](10) Not NULL,
	[Cart_Log_Id]					[int] NULL,
	[Load_Date]                     [Datetime] not null,
	[Update_Date]                   [Datetime] null, 
 CONSTRAINT [PK_comp_reg] PRIMARY KEY CLUSTERED 
(
	[Complaint_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


